### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by olivroy** [rstudio/keras3#1457]
![image](https://github.com/rstudio/keras3/assets/52606734/b8d2a0e5-9ef0-42cb-a025-5eb452e069ef)

Could a redirect to https://keras3.posit.co be enabled?

**Comment by t-kalinowski** [comment]
Thanks! We're actively working on this, the redirect should be working soon.

**Comment by t-kalinowski** [comment]
Fixed now. Thanks for reporting!
