### ISSUE TITLE
Support Torch for R as backend in keras?

### ISSUE THREAD

**Issue by florianhartig** [rstudio/keras3#1460]
Hi,

nor sure if this is a question to the keras3 R package or keras3 as a framework, but I was wondering if there are any options or plans support Torch for R as an alternative to PyTorch when working with keras from R?

**Comment by t-kalinowski** [comment]
Hi, thanks for asking. There are currently no plans to add an R torch backend to Keras. Doing so would be an enormous effort, and in my opinion, somewhat counter productive. 

One of the benefits of the reticulate Python integration is that R users get full access to everything in the Python community *and* the R community. Moving to a pure R backend would neutralize some of that benefit. However, with that said, if you're looking for a keras-like interface that is pure R, you might enjoy https://github.com/mlverse/luz.
