### ISSUE TITLE
k_argmax() fails

### ISSUE THREAD

**Issue by leedrake5** [rstudio/keras3#849]
If I run the dummy code:

```
###Create simple vector
test.vector <- c(1, 2, 3, 4, 5)

###Prep the Data
test.to.cat <- to_categorical(test.vector, num_classes=6)

###Return the data to its original form
test.back <- k_argmax(x=test.to.cat, -1)
```

I get the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: __init__() got an unexpected keyword argument 'x'
> 
> Detailed traceback: 
>   File "/Users/lee/anaconda3/lib/python3.6/site-packages/plaidml/tile.py", line 255, in function
>     operation = cls(*args, **kwargs)

I tried using ramify::argmax, but it doesn't return the same data that I input. So for now, I honestly have no idea how to actually apply a categorical classifier in R. 

Any insight on what I am doing wrong, and if there is any way to make this work would be appreciated. Though from the error, it sounds like x is not being passed to python correctly. 

I am using PlaidML - if this bug should be filed there please let me know.

**Comment by danli349** [comment]
@leedrake5 
It seems `k_argmax` function only exists in `keras`, not exists in `keras3` package.

```{r}
###Create simple vector
test.vector <- c(1, 2, 3, 4, 5)

###Prep the Data
test.to.cat <- to_categorical(test.vector, num_classes=6)

###Return the data to its original form
test.back <- keras::k_argmax(x=test.to.cat, -1)
test.back
```
```{r}
tf.Tensor([1 2 3 4 5], shape=(5), dtype=int64)
```

**Comment by t-kalinowski** [comment]
In `keras3`, you can use [`keras3::op_argmax`](https://keras3.posit.co/reference/op_argmax.html)
